<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LabelGenerator.Core\LabelGenerator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LabelGenerator.App\Config\appsettings.json"
          Link="Config\appsettings.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\LabelGenerator.App\lng\**\*"
          Link="lng\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\LabelGenerator.App\info.txt"
          Link="info.txt"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\LabelGenerator.App\logo.jpg"
          Link="logo.jpg"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\LabelGenerator.App\log.jpg"
          Link="log.jpg"
          CopyToOutputDirectory="PreserveNewest"
          Condition="Exists('..\LabelGenerator.App\log.jpg')" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
